# --- Base Stage ---
FROM node/6 as base
# Construct directories
RUN mdkir -p /usr/src/app
# set directory
WORKDIR /usr/src/app
# load packages
COPY server/package.json /usr/src/app/

# --- Build Stage ---
FROM base as dependancies 
# install production dependancies
RUN npm set progress=false && npm config set depth 0
RUN npm install --only=production
# cache the production modules
RUN cp -R node_modules prod_node_modules
# install all dependancies
RUN npm install
COPY server/ /usr/src/app

# --- Test Stage ---
FROM dependancies AS test
RUN npm run test

# --- Dev Stage ---
FROM dependancies AS develop
EXPOSE 80
ENV PORT 80
ENV production_env 1
RUN npm run dev
